version: "3.1"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
        ports:
          - "9300:9300"
          - "9200:9200"
        environment:
            discovery.type: single-node
          
    kibana:
        image: docker.elastic.co/kibana/kibana:6.2.2
        ports:
          - "5601:5601"